package com.chainsentinel.web.auth;

public enum AuthErrorCode {
	AUTH_INVALID_CREDENTIALS,
	AUTH_LOGIN_LOCKED,
	AUTH_TOKEN_MISSING,
	AUTH_TOKEN_INVALID,
	AUTH_ROLE_FORBIDDEN,
	AUTH_REFRESH_TOKEN_INVALID
}
