package com.chainsentinel.web.auth;

public enum AuthErrorCode {
	AUTH_INVALID_CREDENTIALS,
	AUTH_LOGIN_LOCKED,
	AUTH_PASSWORD_INVALID,
	AUTH_PASSWORD_WEAK,
	AUTH_USERNAME_INVALID,
	AUTH_USER_NOT_FOUND,
	AUTH_ROLE_INVALID,
	AUTH_USERNAME_CONFLICT,
	AUTH_TOKEN_MISSING,
	AUTH_TOKEN_INVALID,
	AUTH_ROLE_FORBIDDEN,
	AUTH_REFRESH_TOKEN_INVALID
}
