CREATE TABLE IF NOT EXISTS trade_account (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(64) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    account_type VARCHAR(16) NOT NULL DEFAULT 'API_KEY',
    env_type VARCHAR(16) NOT NULL DEFAULT 'SIMULATED',
    api_key VARCHAR(255) DEFAULT NULL,
    api_secret_cipher VARCHAR(1024) DEFAULT NULL,
    passphrase_cipher VARCHAR(1024) DEFAULT NULL,
    enabled BIT(1) NOT NULL DEFAULT b'1',
    remark VARCHAR(255) DEFAULT NULL,
    created_by BIGINT DEFAULT NULL,
    updated_by BIGINT DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_trade_account_provider_name (provider, name),
    KEY idx_trade_account_enabled_provider (enabled, provider),
    KEY idx_trade_account_created_by (created_by),
    KEY idx_trade_account_updated_by (updated_by),
    CONSTRAINT fk_trade_account_created_by FOREIGN KEY (created_by) REFERENCES auth_user (id) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT fk_trade_account_updated_by FOREIGN KEY (updated_by) REFERENCES auth_user (id) ON DELETE SET NULL ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Trading account configuration and encrypted credentials';

CREATE TABLE IF NOT EXISTS trade_order (
    id BIGINT NOT NULL AUTO_INCREMENT,
    account_id BIGINT NOT NULL,
    client_order_id VARCHAR(64) NOT NULL,
    provider VARCHAR(32) NOT NULL,
    market_type VARCHAR(16) NOT NULL DEFAULT 'SPOT',
    symbol VARCHAR(64) NOT NULL,
    side VARCHAR(16) NOT NULL,
    order_type VARCHAR(16) NOT NULL,
    price DECIMAL(38, 18) DEFAULT NULL,
    quantity DECIMAL(38, 18) NOT NULL,
    quote_amount DECIMAL(38, 18) DEFAULT NULL,
    status VARCHAR(32) NOT NULL,
    provider_order_id VARCHAR(64) DEFAULT NULL,
    avg_fill_price DECIMAL(38, 18) DEFAULT NULL,
    filled_quantity DECIMAL(38, 18) NOT NULL DEFAULT 0.000000000000000000,
    filled_amount DECIMAL(38, 18) NOT NULL DEFAULT 0.000000000000000000,
    raw_response_json JSON DEFAULT NULL,
    error_code VARCHAR(64) DEFAULT NULL,
    error_message VARCHAR(255) DEFAULT NULL,
    created_by BIGINT DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_trade_order_client_order_id (client_order_id),
    UNIQUE KEY uk_trade_order_provider_order_id (provider, provider_order_id),
    KEY idx_trade_order_account_created_at (account_id, created_at),
    KEY idx_trade_order_symbol_status (symbol, status),
    KEY idx_trade_order_created_by (created_by),
    CONSTRAINT fk_trade_order_account_id FOREIGN KEY (account_id) REFERENCES trade_account (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_trade_order_created_by FOREIGN KEY (created_by) REFERENCES auth_user (id) ON DELETE SET NULL ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Trading order records with local and provider status mapping';

CREATE TABLE IF NOT EXISTS trade_fill (
    id BIGINT NOT NULL AUTO_INCREMENT,
    order_id BIGINT NOT NULL,
    provider_fill_id VARCHAR(64) NOT NULL,
    symbol VARCHAR(64) NOT NULL,
    side VARCHAR(16) NOT NULL,
    price DECIMAL(38, 18) NOT NULL,
    quantity DECIMAL(38, 18) NOT NULL,
    fee DECIMAL(38, 18) DEFAULT NULL,
    fee_currency VARCHAR(16) DEFAULT NULL,
    filled_at TIMESTAMP NULL DEFAULT NULL,
    raw_response_json JSON DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_trade_fill_order_provider_fill (order_id, provider_fill_id),
    KEY idx_trade_fill_symbol_filled_at (symbol, filled_at),
    CONSTRAINT fk_trade_fill_order_id FOREIGN KEY (order_id) REFERENCES trade_order (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Trade fill details synchronized from provider';

CREATE TABLE IF NOT EXISTS trade_account_balance_snapshot (
    id BIGINT NOT NULL AUTO_INCREMENT,
    account_id BIGINT NOT NULL,
    asset VARCHAR(32) NOT NULL,
    available DECIMAL(38, 18) NOT NULL DEFAULT 0.000000000000000000,
    frozen DECIMAL(38, 18) NOT NULL DEFAULT 0.000000000000000000,
    total DECIMAL(38, 18) NOT NULL DEFAULT 0.000000000000000000,
    source VARCHAR(32) NOT NULL DEFAULT 'HTTP',
    snapshot_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_trade_balance_account_asset_snapshot (account_id, asset, snapshot_time),
    KEY idx_trade_balance_account_snapshot (account_id, snapshot_time),
    CONSTRAINT fk_trade_balance_account_id FOREIGN KEY (account_id) REFERENCES trade_account (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Trading account asset balance snapshots for asset overview and funding checks';

CREATE TABLE IF NOT EXISTS trade_position_snapshot (
    id BIGINT NOT NULL AUTO_INCREMENT,
    account_id BIGINT NOT NULL,
    symbol VARCHAR(64) NOT NULL,
    base_asset VARCHAR(32) NOT NULL,
    quote_asset VARCHAR(32) NOT NULL,
    quantity DECIMAL(38, 18) NOT NULL DEFAULT 0.000000000000000000,
    avg_cost DECIMAL(38, 18) DEFAULT NULL,
    market_price DECIMAL(38, 18) DEFAULT NULL,
    market_value DECIMAL(38, 18) DEFAULT NULL,
    unrealized_pnl DECIMAL(38, 18) DEFAULT NULL,
    unrealized_pnl_ratio DECIMAL(38, 18) DEFAULT NULL,
    source VARCHAR(32) NOT NULL DEFAULT 'HTTP',
    snapshot_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_trade_position_account_symbol_snapshot (account_id, symbol, snapshot_time),
    KEY idx_trade_position_account_snapshot (account_id, snapshot_time),
    CONSTRAINT fk_trade_position_account_id FOREIGN KEY (account_id) REFERENCES trade_account (id) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Trading position snapshots for holdings analysis and PnL views';

CREATE TABLE IF NOT EXISTS trade_audit_log (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT DEFAULT NULL,
    username VARCHAR(64) DEFAULT NULL,
    action VARCHAR(64) NOT NULL,
    account_id BIGINT DEFAULT NULL,
    order_id BIGINT DEFAULT NULL,
    result VARCHAR(16) NOT NULL DEFAULT 'SUCCESS',
    request_summary VARCHAR(1024) DEFAULT NULL,
    trace_id VARCHAR(64) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_trade_audit_user_created_at (user_id, created_at),
    KEY idx_trade_audit_account_created_at (account_id, created_at),
    KEY idx_trade_audit_order_created_at (order_id, created_at),
    KEY idx_trade_audit_action_created_at (action, created_at),
    CONSTRAINT fk_trade_audit_user_id FOREIGN KEY (user_id) REFERENCES auth_user (id) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT fk_trade_audit_account_id FOREIGN KEY (account_id) REFERENCES trade_account (id) ON DELETE SET NULL ON UPDATE RESTRICT,
    CONSTRAINT fk_trade_audit_order_id FOREIGN KEY (order_id) REFERENCES trade_order (id) ON DELETE SET NULL ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Trade operation audit log for account and order actions';
